name: CICD

on:
  workflow_dispatch:
    inputs:
      environments:
        description: This is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from github"
        

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Contianer
        run: echo "Docker contianer build"

  test:
    needs: [code, build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deploying the app"
      
